name: Push

on:
  push:
    branches: [ '**' ]
    paths-ignore: [ '**.md' ]

jobs:
  push:
    uses: ./.github/workflows/build.yml
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}


